language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

cache:
  directories:
    - vendor

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

matrix:
  allow_failures:
    - php: nightly

script:
  - composer update $COMPOSER_PREFER
  - "[[ \"$TRAVIS_PHP_VERSION\" == '7.1' ]] && composer require 'atoum/atoum:dev-3.0.x-dev' || true"
  - "[[ \"$TRAVIS_PHP_VERSION\" != '5.3' && \"$TRAVIS_PHP_VERSION\" != '5.4' && \"$TRAVIS_PHP_VERSION\" != '7.1' ]] && composer require --dev 'atoum/reports-extension:^2.0.1' || true"
  - bin/atoum -ncc

notifications:
    irc: "irc.freenode.org##atoum"
