language: php
sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

script:
  - composer update $COMPOSER_PREFER
  - bin/atoum -ncc

notifications:
    irc: "irc.freenode.org##atoum"
