language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

cache:
  directories:
    - vendor

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

matrix:
  exclude:
    - php: 7.1
      env: COMPOSER_PREFER="--prefer-lowest"

script:
  - composer update $COMPOSER_PREFER
  - "[[ \"$TRAVIS_PHP_VERSION\" == '7.1' ]] && composer require 'atoum/atoum:dev-3.0.x-dev' || true"
  - "[[ \"$TRAVIS_PHP_VERSION\" != '5.3' && \"$TRAVIS_PHP_VERSION\" != '5.4' && \"$TRAVIS_PHP_VERSION\" != '7.1' ]] && composer require --dev 'atoum/reports-extension:^2.0.1' || true"
  - bin/atoum -ncc

notifications:
    irc: "irc.freenode.org##atoum"
